---
version: '3.6'

networks:
  swarm:
    driver: "bridge"

services:
  control:
    image: docker:dind
    privileged: true
    ports:
      - 2375:2375
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - swarm
  manager:
    image: docker:dind
    privileged: true
    networks:
      - swarm
  worker:
    image: docker:dind
    privileged: true
    networks:
      - swarm
